name: GitHub-Profile-Summary-Cards-v2
on:
  schedule: # execute every 24 hours
    - cron: '* */24 * * *'
  workflow_dispatch:
jobs:
  Card:
    runs-on: ubuntu-latest
    steps:
      - name: generate profile card
        uses: ervitis/github-profile-summary-cards@draft
        with:
          USERNAME: ${{ github.repository_owner }}
